# Generated by Django 5.2 on 2025-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='adresse',
        ),
        migrations.AddField(
            model_name='client',
            name='gouvernorat',
            field=models.CharField(blank=True, choices=[('Ariana', 'Ariana'), ('Béja', 'Béja'), ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Gabès', 'Gabès'), ('Gafsa', 'Gafsa'), ('Jendouba', 'Jendouba'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Kébili', 'Kébili'), ('Le Kef', 'Le Kef'), ('Mahdia', 'Mahdia'), ('La Manouba', 'La Manouba'), ('Médenine', 'Médenine'), ('Monastir', 'Monastir'), ('Nabeul', 'Nabeul'), ('Sfax', 'Sfax'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Tataouine', 'Tataouine'), ('Tozeur', 'Tozeur'), ('Tunis', 'Tunis'), ('Zaghouan', 'Zaghouan')], max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='pays',
            field=models.CharField(choices=[('Tunisie', 'Tunisie'), ('Algérie', 'Algérie'), ('Maroc', 'Maroc'), ('France', 'France'), ('Italie', 'Italie'), ('Autre', 'Autre')], default='Tunisie', max_length=50),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='gouvernorat',
            field=models.CharField(blank=True, choices=[('Ariana', 'Ariana'), ('Béja', 'Béja'), ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Gabès', 'Gabès'), ('Gafsa', 'Gafsa'), ('Jendouba', 'Jendouba'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Kébili', 'Kébili'), ('Le Kef', 'Le Kef'), ('Mahdia', 'Mahdia'), ('La Manouba', 'La Manouba'), ('Médenine', 'Médenine'), ('Monastir', 'Monastir'), ('Nabeul', 'Nabeul'), ('Sfax', 'Sfax'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Tataouine', 'Tataouine'), ('Tozeur', 'Tozeur'), ('Tunis', 'Tunis'), ('Zaghouan', 'Zaghouan')], max_length=50),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='pays',
            field=models.CharField(choices=[('Tunisie', 'Tunisie'), ('Algérie', 'Algérie'), ('Maroc', 'Maroc'), ('France', 'France'), ('Italie', 'Italie'), ('Autre', 'Autre')], default='Tunisie', max_length=50),
        ),
    ]
