# Generated by Django 5.2 on 2025-04-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_produit_prix_unitaire_mouvementstock_depense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='revenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
